# (Negative) Urgency (all items except 1 are reversed)
# items 2 (R), 7(R), 12 (R), 17 (R), 22 (R), 29 (R), 34 (R), 39 (R), 44 (R), 50 (R), 53, 58 (R)  # noqa
# (lack of) Premeditation (no items are reversed)
# items 1, 6, 11, 16, 21, 28, 33, 38, 43, 48, 55.
# (lack of) Perseverance (two items are reversed)
# items 4, 9 (R), 14, 19, 24, 27, 32, 37, 42, 47 (R)
# Sensation Seeking (all items are reversed)
# items 3 (R), 8 (R), 13 (R), 18 (R), 23 (R), 26 (R), 31 (R), 36 (R), 41 (R), 46 (R), 51 (R), 56 (R)  # noqa
# Positive Urgency (all items are reversed)
# items 5 (R), 10 (R), 15 (R), 20 (R), 25 (R), 30 (R), 35 (R), 40 (R), 45 (R), 49 (R), 52 (R), 54 (R), 57 (R), 59 (R)  # noqa
uppsp_dict = {
    "uppsp.1": "lack_premed",
    "uppsp.2": "neg_urgency",
    "uppsp.3": "sens_seeking",
    "uppsp.4": "persev",
    "uppsp.5": "positive_urgency",
    "uppsp.6": "lack_premed",
    "uppsp.7": "neg_urgency",
    "uppsp.8": "sens_seeking",
    "uppsp.9": "persev",
    "uppsp.10": "positive_urgency",
    "uppsp.11": "lack_premed",
    "uppsp.12": "neg_urgency",
    "uppsp.13": "sens_seeking",
    "uppsp.14": "persev",
    "uppsp.15": "positive_urgency",
    "uppsp.16": "lack_premed",
    "uppsp.17": "neg_urgency",
    "uppsp.18": "sens_seeking",
    "uppsp.19": "persev",
    "uppsp.20": "positive_urgency",
    "uppsp.21": "lack_premed",
    "uppsp.22": "neg_urgency",
    "uppsp.23": "sens_seeking",
    "uppsp.24": "persev",
    "uppsp.25": "positive_urgency",
    "uppsp.26": "sens_seeking",
    "uppsp.27": "persev",
    "uppsp.28": "lack_premed",
    "uppsp.29": "neg_urgency",
    "uppsp.30": "positive_urgency",
    "uppsp.31": "sens_seeking",
    "uppsp.32": "persev",
    "uppsp.33": "lack_premed",
    "uppsp.34": "neg_urgency",
    "uppsp.35": "positive_urgency",
    "uppsp.36": "sens_seeking",
    "uppsp.37": "persev",
    "uppsp.38": "lack_premed",
    "uppsp.39": "neg_urgency",
    "uppsp.40": "positive_urgency",
    "uppsp.41": "sens_seeking",
    "uppsp.42": "persev",
    "uppsp.43": "lack_premed",
    "uppsp.44": "neg_urgency",
    "uppsp.45": "positive_urgency",
    "uppsp.46": "sens_seeking",
    "uppsp.47": "persev",
    "uppsp.48": "lack_premed",
    "uppsp.49": "positive_urgency",
    "uppsp.50": "neg_urgency",
    "uppsp.51": "sens_seeking",
    "uppsp.52": "positive_urgency",
    "uppsp.53": "neg_urgency",
    "uppsp.54": "positive_urgency",
    "uppsp.55": "lack_premed",
    "uppsp.56": "sens_seeking",
    "uppsp.57": "positive_urgency",
    "uppsp.58": "neg_urgency",
    "uppsp.59": "positive_urgency",
}
