project_path = $(save_path:/work/vfelso)/planning-depth-differences
executable = $(project_path)/env/bin/python
filename = $(project_path)/cluster/src/get_q_values.py
arguments = $(filename) -s $(experiment_setting:high_increasing) -c $(cost_function:back_dist_depth_eff_forw) -n $(file_number) -l=$(reward_line)
output = log/$(output_string:out_3).stdout
error  = log/$(output_string:out_3).stderr
log   = log/$(output_string:out_3).log
request_memory = 50000
request_cpus = 1

queue
