project_path = $(save_path:/work/vfelso)/planning-depth-differences
executable = $(project_path)/env/bin/python
filename = $(project_path)/cluster/src/reduce_q_file_sizes.py
arguments = $(filename) -s $(experiment_setting:high_increasing) -c $(cost_function:linear_depth)
output = log/$(output_string:out_3_reduce).stdout
error  = log/$(output_string:out_3_reduce).stderr
log   = log/$(output_string:out_3_reduce).log
request_memory = 50000
request_cpus = 1

queue
