project_path = $(save_path:/work/vfelso)/planning-depth-differences
executable = $(project_path)/env/bin/python
filename = $(project_path)/cluster/submission_scripts/MPI-IS/05_Combine_Human.py
arguments = $(filename) -e $(experiment:CogSci2020) -c $(cost_function:dist_depth_eff_forw) -a=$(alpha:1)
output = log/$(output_string:out_5).stdout
error  = log/$(output_string:out_5).stderr
log   = log/$(output_string:out_5).log
request_memory = 200000
request_cpus = 1

queue
