project_path = $(save_path:/home/jliu)/planning-depth-differences
executable = $(project_path)/env/bin/python
filename = $(project_path)/cluster/src/simulate_trajectories.py
arguments = $(filename) -p $(policy:RandomPolicy) -e $(experiment_setting:high_increasing)
output = log/$(output_string:out_6).stdout
error  = log/$(output_string:out_6).stderr
log   = log/$(output_string:out_6).log
request_memory = 30000
request_cpus = 1

queue
