project_path = $(save_path:/work/vfelso)/planning-depth-differences
executable = $(project_path)/env/bin/python
filename = $(project_path)/cluster/submission_scripts/MPI-IS/08_Combine_Inferred.py
arguments = $(filename) -p $(policy:SoftmaxPolicy) -c $(cost_function:dist_depth_eff_forw)
output = log/$(output_string:out_8).stdout
error  = log/$(output_string:out_8).stderr
log   = log/$(output_string:out_8).log
request_memory = 900000
request_cpus = 1

queue
