project_path = $(save_path:/home/vfelso)/irl-project
executable = $(project_path)/env/bin/python
filename = $(project_path)/cluster/submission_scripts/MPI-IS/08_Combine_Inferred.py
arguments = $(filename) -p $(policy:SoftmaxPolicy) -c $(cost_function:linear_depth)
output = log/$(output_string:out_8).stdout
error  = log/$(output_string:out_8).stderr
log   = log/$(output_string:out_8).log
request_memory = 100000
request_cpus = 1

queue
