project_path = $(save_path:/home/vfelso)/planning-depth-differences
executable = $(project_path)/env/bin/python
filename = $(project_path)/analysis/methods/static/src/extract_marginal_likelihood_and_hdis.py
arguments = $(filename) -e $(experiment:ValidationExperiment) -c $(cost_function:linear_depth)
output = log/$(output_string:out_10).stdout
error  = log/$(output_string:out_10).stderr
log   = log/$(output_string:out_10).log
request_memory = 300000
request_cpus = 1

queue
