project_path = $(save_path:/home/vfelso)/irl-project
executable = $(project_path)/env/bin/python
filename = $(project_path)/analysis/methods/static/src/get_optimal_bic.py
arguments = $(filename) -e $(experiment:OptimalBIC)
output = $(project_path)/analysis/methods/static/log/$(output_string:out_M2).stdout
error  = log/$(output_string:out_M2).stderr
log   = log/$(output_string:out_M2).log
request_memory = 10000
request_cpus = 1

queue
