project_path = $(save_path:/home/jliu)/planning-depth-differences
executable = $(project_path)/env/bin/python
filename = $(project_path)/analysis/methods/static/src/find_stable_point_with_cm.py
arguments = $(filename) -e $(experiment:MainExperiment)
output = $(project_path)/analysis/methods/static/log/$(output_string:out_M3).stdout
error  = log/$(output_string:out_M3).stderr
log   = log/$(output_string:out_M3).log
request_memory = 10000
request_cpus = 1

queue
