project_path = $(save_path:/work/vfelso)/planning-depth-differences
executable = $(project_path)/env/bin/python
filename = $(project_path)/analysis/methods/static/src/plot_bms.py
arguments = $(filename) -e $(experiment:MainExperiment) -s $(subdirectory:methods/static)
output = $(project_path)/analysis/methods/static/log/$(output_string:out_M5).stdout
error  = log/$(output_string:out_M5).stderr
log   = log/$(output_string:out_M5).log
request_memory = 40000
request_cpus = 1

queue
