project_path = $(save_path:/home/vfelso)/irl-project
executable = $(project_path)/env/bin/python
filename = $(project_path)/analysis/methods/static/src/plot_participant_average_likelihoods.py
arguments = $(filename) -e $(experiment:TrialByTrial)
output = $(project_path)/analysis/methods/static/log/$(output_string:out_M6).stdout
error  = log/$(output_string:out_M6).stderr
log   = log/$(output_string:out_M6).log
request_memory = 50000
request_cpus = 1

queue
