project_path = $(save_path:/work/vfelso)/planning-depth-differences
executable = $(project_path)/env/bin/python
filename = $(project_path)/analysis/methods/static/src/regression_cross_validation.py
arguments = $(filename) -e $(experiment:ValidationExperiment) -s $(subdirectory:methods/static)
output = $(project_path)/analysis/$(subdirectory:methods/static)/log/$(output_string:out_M12).stdout
error  = log/$(output_string:out_M12).stderr
log   = log/$(output_string:out_M12).log
request_memory = 10000
request_cpus = 1

queue
