project_path = $(save_path:/work/vfelso)/planning-depth-differences
executable = $(project_path)/env/bin/python
filename = $(project_path)/analysis/methods/static/src/regression_cross_validation.py
arguments = $(filename)
output = $(project_path)/analysis/$(subdirectory:methods/static)/log/regression_$(experiment:ValidationExperiment).stdout
error  = log/regression_$(experiment:ValidationExperiment).stderr
log   = log/regression_$(experiment:ValidationExperiment).log
request_memory = 10000
request_cpus = 1

queue
