project_path = $(save_path:/home/vfelso)/irl-project
executable = $(project_path)/env/bin/python
filename = $(project_path)/analysis/methods/static/src/plot_validation_hdi.py
arguments = $(filename) -e $(experiment:ValidationExperiment) -c $(cost_function:linear_depth)
output = $(project_path)/analysis/methods/static/log/$(output_string:out_M13).stdout
error  = log/$(output_string:out_M13).stderr
log   = log/$(output_string:out_M13).log
request_memory = 20000
request_cpus = 1

queue
