project_path = $(save_path:/work/vfelso)/planning-depth-differences
executable = $(project_path)/env/bin/python
filename = $(project_path)/analysis/methods/static/src/plot_simulated_info.py
arguments = $(filename)
output = $(project_path)/analysis/$(subdirectory:methods/static)/log/$(output_string:Simulated_Info).stdout
error  = log/$(output_string:Simulated_Info).stderr
log   = log/$(output_string:Simulated_Info).log
request_memory = 20000
request_cpus = 1

queue
