project_path = $(save_path:/work/vfelso)/planning-depth-differences
executable = $(project_path)/env/bin/python
filename = $(project_path)/analysis/methods/static/src/plot_all_vs_test.py
arguments = $(filename)
output = $(project_path)/analysis/$(subdirectory:methods/static)/log/$(output_string:AllTrials).stdout
error  = log/$(output_string:AllTrials).stderr
log   = log/$(output_string:AllTrials).log
request_memory =200000
request_cpus = 1

queue
