project_path = $(save_path:/home/vfelso)/irl-project
executable = $(project_path)/env/bin/python
filename = $(project_path)/analysis/methods/static/src/plot_all_vs_test.py
arguments = $(filename) -e $(experiment1:TrialByTrial) -f $(experiment2:TrialByTrialAll)
output = $(project_path)/analysis/methods/static/log/$(output_string:out_M15).stdout
error  = log/$(output_string:out_M15).stderr
log   = log/$(output_string:out_M15).log
request_memory =200000
request_cpus = 1

queue
