project_path = $(save_path:/home/jliu)/planning-depth-differences
executable = $(project_path)/env/bin/python
filename = $(project_path)/analysis/methods/static/src/plot_main_hdi.py
arguments = $(filename) -e $(experiment:MainExperiment) -c $(cost_function:linear_depth)
output = $(project_path)/analysis/methods/static/log/$(output_string:out_M16).stdout
error  = log/$(output_string:out_M16).stderr
log   = log/$(output_string:out_M16).log
request_memory = 50000
request_cpus = 1

queue
